package com.telpo.usb.finger.serverentities;
// Generated Jun 30, 2018 8:14:16 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Basicfarmerinfo generated by hbm2java
 */

public class Basicfarmerinfo implements java.io.Serializable {

    private Integer id;
    private String regagent;
    private String uniqueuid;
    private String farmerid;
    private String surname;
    private String othernames;
    private String othername;
    private Date dateofbirth;
    private String placeofbirth;
    private String gender;
    private String hometown;
    private String address;
    private String tel;
    private String levelofeducation;
    private String religion;
    private String maritalstatus;
    private String community;
    private String district;
    private String region;
    private String country;
    private Date datecreated;
    private Character pending;
    private String agentid;
    private String agentname;
    private String imei;
    private String macaddress;
    private String email;
    private String funding;
    private String postbox;
    private Integer serverid;
    private String aggregatorid;
    public Basicfarmerinfo() {
    }

    public String getAggregatorid() {
        return aggregatorid;
    }

    public void setAggregatorid(String aggregatorid) {
        this.aggregatorid = aggregatorid;
    }

    public Integer getServerid() {
        return serverid;
    }

    public void setServerid(Integer serverid) {
        this.serverid = serverid;
    }

    public String getOthername() {
        return othername;
    }

    public void setOthername(String othername) {
        this.othername = othername;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRegagent() {
        return regagent;
    }

    public void setRegagent(String regagent) {
        this.regagent = regagent;
    }

    public String getUniqueuid() {
        return uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }

    public String getFarmerid() {
        return farmerid;
    }

    public void setFarmerid(String farmerid) {
        this.farmerid = farmerid;
    }

    public String getSurname() {
        return surname;
    }

    public void setSurname(String surname) {
        this.surname = surname;
    }

    public String getOthernames() {
        return othernames;
    }

    public void setOthernames(String othernames) {
        this.othernames = othernames;
    }

    public Date getDateofbirth() {
        return dateofbirth;
    }

    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    public String getPlaceofbirth() {
        return placeofbirth;
    }

    public void setPlaceofbirth(String placeofbirth) {
        this.placeofbirth = placeofbirth;
    }

    public String getGender() {
        return gender;
    }

    public void setGender(String gender) {
        this.gender = gender;
    }

    public String getHometown() {
        return hometown;
    }

    public void setHometown(String hometown) {
        this.hometown = hometown;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTel() {
        return tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getLevelofeducation() {
        return levelofeducation;
    }

    public void setLevelofeducation(String levelofeducation) {
        this.levelofeducation = levelofeducation;
    }

    public String getReligion() {
        return religion;
    }

    public void setReligion(String religion) {
        this.religion = religion;
    }

    public String getMaritalstatus() {
        return maritalstatus;
    }

    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus;
    }

    public String getCommunity() {
        return community;
    }

    public void setCommunity(String community) {
        this.community = community;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Date getDatecreated() {
        return datecreated;
    }

    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }

    public Character getPending() {
        return pending;
    }

    public void setPending(Character pending) {
        this.pending = pending;
    }

    public String getAgentid() {
        return agentid;
    }

    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    public String getAgentname() {
        return agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public String getImei() {
        return imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getMacaddress() {
        return macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getFunding() {
        return funding;
    }

    public void setFunding(String funding) {
        this.funding = funding;
    }

    public String getPostbox() {
        return postbox;
    }

    public void setPostbox(String postbox) {
        this.postbox = postbox;
    }

    @Override
    public String toString() {
        return "Basicfarmerinfo{" +
                "id=" + id +
                ", regagent='" + regagent + '\'' +
                ", uniqueuid='" + uniqueuid + '\'' +
                ", farmerid='" + farmerid + '\'' +
                ", surname='" + surname + '\'' +
                ", othernames='" + othernames + '\'' +
                ", dateofbirth=" + dateofbirth +
                ", placeofbirth='" + placeofbirth + '\'' +
                ", gender='" + gender + '\'' +
                ", hometown='" + hometown + '\'' +
                ", address='" + address + '\'' +
                ", tel='" + tel + '\'' +
                ", levelofeducation='" + levelofeducation + '\'' +
                ", religion='" + religion + '\'' +
                ", maritalstatus='" + maritalstatus + '\'' +
                ", community='" + community + '\'' +
                ", district='" + district + '\'' +
                ", region='" + region + '\'' +
                ", country='" + country + '\'' +
                ", datecreated=" + datecreated +
                ", pending=" + pending +
                ", agentid='" + agentid + '\'' +
                ", agentname='" + agentname + '\'' +
                ", imei='" + imei + '\'' +
                ", macaddress='" + macaddress + '\'' +
                ", email='" + email + '\'' +
                ", funding='" + funding + '\'' +
                ", postbox='" + postbox + '\'' +
                '}';
    }
}


