package com.telpo.usb.finger.serverentities;
// Generated Jul 1, 2018 11:03:25 PM by Hibernate Tools 4.3.1


/**
 * Districts generated by hbm2java
 */

public class Districts implements java.io.Serializable {

    private Integer id;
    private String district;
    private String districtcode;
    private Integer targets;
    private String regioncode;
    private String region;

    public Districts() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getDistrictcode() {
        return districtcode;
    }

    public void setDistrictcode(String districtcode) {
        this.districtcode = districtcode;
    }

    public Integer getTargets() {
        return targets;
    }

    public void setTargets(Integer targets) {
        this.targets = targets;
    }

    public String getRegioncode() {
        return regioncode;
    }

    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }
}


