package com.telpo.usb.finger.serverentities;
// Generated Jun 30, 2018 8:14:16 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Farminfo generated by hbm2java
 */

public class Farminfo implements java.io.Serializable {


    private Integer id;
    private String farmerid;
    private String farmid;
    private String uniqueuid;
    private String community;
    private String district;
    private String region;
    private Double totalarea;
    private Double cultivatedarea;
    private Integer shadetrees;
    private String materialsource;
    private String ownershipmethod;
    private String extprovider;
    private String laboursource;
    private String typeoffarm;
    private String farmspecialty;
    private String otheractivities;
    private String yearofestablishment;
    private byte[] picture;
    private Date dateregistered;
    private String pending;
    private String agentid;
    private String agentname;
    private String imei;
    private String macaddress;
    private String chemicalused;
    private String cropprotection;
    private String cropvariety;
    private String farmyield;
    private String fertilizerused;
    private String extension;
    private String othersource;
    private String organisation;
    private String aggregatorid;

    public String getAggregatorid() {
        return aggregatorid;
    }

    public void setAggregatorid(String aggregatorid) {
        this.aggregatorid = aggregatorid;
    }
    public Farminfo() {
    }


    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getFarmerid() {
        return farmerid;
    }

    public void setFarmerid(String farmerid) {
        this.farmerid = farmerid;
    }

    public String getFarmid() {
        return farmid;
    }

    public void setFarmid(String farmid) {
        this.farmid = farmid;
    }

    public String getUniqueuid() {
        return uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }

    public String getCommunity() {
        return community;
    }

    public void setCommunity(String community) {
        this.community = community;
    }

    public String getDistrict() {
        return district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public Double getTotalarea() {
        return totalarea;
    }

    public void setTotalarea(Double totalarea) {
        this.totalarea = totalarea;
    }

    public Double getCultivatedarea() {
        return cultivatedarea;
    }

    public void setCultivatedarea(Double cultivatedarea) {
        this.cultivatedarea = cultivatedarea;
    }

    public Integer getShadetrees() {
        return shadetrees;
    }

    public void setShadetrees(Integer shadetrees) {
        this.shadetrees = shadetrees;
    }

    public String getMaterialsource() {
        return materialsource;
    }

    public void setMaterialsource(String materialsource) {
        this.materialsource = materialsource;
    }

    public String getOwnershipmethod() {
        return ownershipmethod;
    }

    public void setOwnershipmethod(String ownershipmethod) {
        this.ownershipmethod = ownershipmethod;
    }

    public String getExtprovider() {
        return extprovider;
    }

    public void setExtprovider(String extprovider) {
        this.extprovider = extprovider;
    }

    public String getLaboursource() {
        return laboursource;
    }

    public void setLaboursource(String laboursource) {
        this.laboursource = laboursource;
    }

    public String getTypeoffarm() {
        return typeoffarm;
    }

    public void setTypeoffarm(String typeoffarm) {
        this.typeoffarm = typeoffarm;
    }

    public String getFarmspecialty() {
        return farmspecialty;
    }

    public void setFarmspecialty(String farmspecialty) {
        this.farmspecialty = farmspecialty;
    }

    public String getOtheractivities() {
        return otheractivities;
    }

    public void setOtheractivities(String otheractivities) {
        this.otheractivities = otheractivities;
    }

    public String getYearofestablishment() {
        return yearofestablishment;
    }

    public void setYearofestablishment(String yearofestablishment) {
        this.yearofestablishment = yearofestablishment;
    }

    public byte[] getPicture() {
        return picture;
    }

    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    public Date getDateregistered() {
        return dateregistered;
    }

    public void setDateregistered(Date dateregistered) {
        this.dateregistered = dateregistered;
    }

    public String getPending() {
        return pending;
    }

    public void setPending(String pending) {
        this.pending = pending;
    }

    public String getAgentid() {
        return agentid;
    }

    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    public String getAgentname() {
        return agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public String getImei() {
        return imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getMacaddress() {
        return macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getChemicalused() {
        return chemicalused;
    }

    public void setChemicalused(String chemicalused) {
        this.chemicalused = chemicalused;
    }

    public String getCropprotection() {
        return cropprotection;
    }

    public void setCropprotection(String cropprotection) {
        this.cropprotection = cropprotection;
    }

    public String getCropvariety() {
        return cropvariety;
    }

    public void setCropvariety(String cropvariety) {
        this.cropvariety = cropvariety;
    }

    public String getFarmyield() {
        return farmyield;
    }

    public void setFarmyield(String farmyield) {
        this.farmyield = farmyield;
    }

    public String getFertilizerused() {
        return fertilizerused;
    }

    public void setFertilizerused(String fertilizerused) {
        this.fertilizerused = fertilizerused;
    }

    public String getExtension() {
        return extension;
    }

    public void setExtension(String extension) {
        this.extension = extension;
    }

    public String getOthersource() {
        return othersource;
    }

    public void setOthersource(String othersource) {
        this.othersource = othersource;
    }

    public String getOrganisation() {
        return organisation;
    }

    public void setOrganisation(String organisation) {
        this.organisation = organisation;
    }
}


