package com.telpo.usb.finger.serverentities;
// Generated Jul 1, 2018 11:03:25 PM by Hibernate Tools 4.3.1


/**
 * Regions generated by hbm2java
 */

public class Regions implements java.io.Serializable {


    private Integer id;
    private String region;
    private String regioncode;

    public Regions() {
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getRegion() {
        return region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getRegioncode() {
        return regioncode;
    }

    public void setRegioncode(String regioncode) {
        this.regioncode = regioncode;
    }
}


