package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


/**
 * Aid generated by hbm2java
 */
public class Aid implements java.io.Serializable {


    private Integer id;
    private String name;
    private String address;
    private String tel;
    private String email;
    private String location;
    private String district;
    private String region;

    public Aid() {
    }

    public Aid(String name, String address, String tel, String email, String location, String district, String region) {
        this.name = name;
        this.address = address;
        this.tel = tel;
        this.email = email;
        this.location = location;
        this.district = district;
        this.region = region;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }


}


