package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


/**
 * Bc generated by hbm2java
 */
public class Bc implements java.io.Serializable {


    public String bcid;
    public String lbcid;
    public String community;
    public String district;
    public String region;
    public String geolocation;

    public Bc() {
    }

    public Bc(String bcid, String lbcid, String community, String district, String region, String geolocation) {
        this.bcid = bcid;
        this.lbcid = lbcid;
        this.community = community;
        this.district = district;
        this.region = region;
        this.geolocation = geolocation;
    }

    public String getBcid() {
        return this.bcid;
    }

    public void setBcid(String bcid) {
        this.bcid = bcid;
    }

    public String getLbcid() {
        return this.lbcid;
    }

    public void setLbcid(String lbcid) {
        this.lbcid = lbcid;
    }

    public String getCommunity() {
        return this.community;
    }

    public void setCommunity(String community) {
        this.community = community;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getGeolocation() {
        return this.geolocation;
    }

    public void setGeolocation(String geolocation) {
        this.geolocation = geolocation;
    }


}


