package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord;

import java.util.Date;

/**
 * FingerprintDuplicates generated by hbm2java
 */
public class FingerprintDuplicates extends SugarRecord {
    private String currentid;
    private String currprint;
    private String duplicateid;
    private String duplprint;
    private Date entrydate;
    private String uniqueuid;

    public FingerprintDuplicates() {
    }

    public FingerprintDuplicates(String currentid, String currprint, String duplicateid, String duplprint, Date entrydate, String uniqueuid) {
        this.currentid = currentid;
        this.currprint = currprint;
        this.duplicateid = duplicateid;
        this.duplprint = duplprint;
        this.entrydate = entrydate;
        this.uniqueuid = uniqueuid;
    }
    public String aggregatorid;

    public String getAggregatorid() {
        return aggregatorid;
    }

    public void setAggregatorid(String aggregatorid) {
        this.aggregatorid = aggregatorid;
    }
    public String getCurrentid() {
        return this.currentid;
    }

    public void setCurrentid(String currentid) {
        this.currentid = currentid;
    }

    public String getCurrprint() {
        return this.currprint;
    }

    public void setCurrprint(String currprint) {
        this.currprint = currprint;
    }

    public String getDuplicateid() {
        return this.duplicateid;
    }

    public void setDuplicateid(String duplicateid) {
        this.duplicateid = duplicateid;
    }

    public String getDuplprint() {
        return this.duplprint;
    }

    public void setDuplprint(String duplprint) {
        this.duplprint = duplprint;
    }

    public Date getEntrydate() {
        return this.entrydate;
    }

    public void setEntrydate(Date entrydate) {
        this.entrydate = entrydate;
    }

    public String getUniqueuid() {
        return this.uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }


}


