package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Invoice generated by hbm2java
 */
public class Invoice implements java.io.Serializable {


    public String macaddress;
    public String imei;
    public String agentname;
    public String agentid;
    private Integer id;
    private String tranId;
    private String distId;
    private String distName;
    private String invoiceNo;
    private Date invoiceDate;
    private String salesPersonId;
    private String salesPersonName;
    private String retailId;
    private String retailName;
    private String email;
    private String phone;
    private String location;
    private String address;
    private String issuedBy;
    private String checkedBy;

    public Invoice() {
    }

    public Invoice(String tranId, String distId, String distName, String invoiceNo, Date invoiceDate, String salesPersonId, String salesPersonName, String retailId, String retailName, String email, String phone, String location, String address, String issuedBy, String checkedBy) {
        this.tranId = tranId;
        this.distId = distId;
        this.distName = distName;
        this.invoiceNo = invoiceNo;
        this.invoiceDate = invoiceDate;
        this.salesPersonId = salesPersonId;
        this.salesPersonName = salesPersonName;
        this.retailId = retailId;
        this.retailName = retailName;
        this.email = email;
        this.phone = phone;
        this.location = location;
        this.address = address;
        this.issuedBy = issuedBy;
        this.checkedBy = checkedBy;
    }

    public String getMacaddress() {
        return macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getImei() {
        return imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getAgentname() {
        return agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public String getAgentid() {
        return agentid;
    }

    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTranId() {
        return this.tranId;
    }

    public void setTranId(String tranId) {
        this.tranId = tranId;
    }

    public String getDistId() {
        return this.distId;
    }

    public void setDistId(String distId) {
        this.distId = distId;
    }

    public String getDistName() {
        return this.distName;
    }

    public void setDistName(String distName) {
        this.distName = distName;
    }

    public String getInvoiceNo() {
        return this.invoiceNo;
    }

    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo;
    }

    public Date getInvoiceDate() {
        return this.invoiceDate;
    }

    public void setInvoiceDate(Date invoiceDate) {
        this.invoiceDate = invoiceDate;
    }

    public String getSalesPersonId() {
        return this.salesPersonId;
    }

    public void setSalesPersonId(String salesPersonId) {
        this.salesPersonId = salesPersonId;
    }

    public String getSalesPersonName() {
        return this.salesPersonName;
    }

    public void setSalesPersonName(String salesPersonName) {
        this.salesPersonName = salesPersonName;
    }

    public String getRetailId() {
        return this.retailId;
    }

    public void setRetailId(String retailId) {
        this.retailId = retailId;
    }

    public String getRetailName() {
        return this.retailName;
    }

    public void setRetailName(String retailName) {
        this.retailName = retailName;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return this.phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getIssuedBy() {
        return this.issuedBy;
    }

    public void setIssuedBy(String issuedBy) {
        this.issuedBy = issuedBy;
    }

    public String getCheckedBy() {
        return this.checkedBy;
    }

    public void setCheckedBy(String checkedBy) {
        this.checkedBy = checkedBy;
    }


}


