package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * InvoiceItems generated by hbm2java
 */
public class InvoiceItems implements java.io.Serializable {


    public String macaddress;
    public String imei;
    public String agentname;
    public String agentid;
    private Integer id;
    private String tranId;
    private String itemName;
    private String itemDescription;
    private int quantity;
    private BigDecimal actualPrice;
    private BigDecimal decountedPrice;
    private BigDecimal weight;
    private BigDecimal totalAmount;

    public InvoiceItems() {
    }

    public InvoiceItems(String tranId, String itemName, String itemDescription, int quantity, BigDecimal actualPrice, BigDecimal decountedPrice, BigDecimal weight, BigDecimal totalAmount) {
        this.tranId = tranId;
        this.itemName = itemName;
        this.itemDescription = itemDescription;
        this.quantity = quantity;
        this.actualPrice = actualPrice;
        this.decountedPrice = decountedPrice;
        this.weight = weight;
        this.totalAmount = totalAmount;
    }

    public String getMacaddress() {
        return macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getImei() {
        return imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getAgentname() {
        return agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public String getAgentid() {
        return agentid;
    }

    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getTranId() {
        return this.tranId;
    }

    public void setTranId(String tranId) {
        this.tranId = tranId;
    }

    public String getItemName() {
        return this.itemName;
    }

    public void setItemName(String itemName) {
        this.itemName = itemName;
    }

    public String getItemDescription() {
        return this.itemDescription;
    }

    public void setItemDescription(String itemDescription) {
        this.itemDescription = itemDescription;
    }

    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getActualPrice() {
        return this.actualPrice;
    }

    public void setActualPrice(BigDecimal actualPrice) {
        this.actualPrice = actualPrice;
    }

    public BigDecimal getDecountedPrice() {
        return this.decountedPrice;
    }

    public void setDecountedPrice(BigDecimal decountedPrice) {
        this.decountedPrice = decountedPrice;
    }

    public BigDecimal getWeight() {
        return this.weight;
    }

    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    public BigDecimal getTotalAmount() {
        return this.totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }


}


