package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


/**
 * Lbc generated by hbm2java
 */
public class Lbc implements java.io.Serializable {


    private String lbcid;
    private String names;
    private String location;
    private String address;
    private String district;
    private String region;
    private String telephone;
    private String email;

    public Lbc() {
    }

    public Lbc(String lbcid, String names, String location, String address, String district, String region, String telephone, String email) {
        this.lbcid = lbcid;
        this.names = names;
        this.location = location;
        this.address = address;
        this.district = district;
        this.region = region;
        this.telephone = telephone;
        this.email = email;
    }

    public String getLbcid() {
        return this.lbcid;
    }

    public void setLbcid(String lbcid) {
        this.lbcid = lbcid;
    }

    public String getNames() {
        return this.names;
    }

    public void setNames(String names) {
        this.names = names;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getRegion() {
        return this.region;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }


}


