package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


/**
 * Pc generated by hbm2java
 */
public class Pc implements java.io.Serializable {


    private String pcid;
    private String lbcid;
    private String buyingcenter;
    private String names;
    private String address;
    private String tel;
    private String email;
    private String location;
    private String imageLocation;

    public Pc() {
    }

    public Pc(String pcid, String lbcid, String buyingcenter, String names, String address, String tel, String email, String location, String imageLocation) {
        this.pcid = pcid;
        this.lbcid = lbcid;
        this.buyingcenter = buyingcenter;
        this.names = names;
        this.address = address;
        this.tel = tel;
        this.email = email;
        this.location = location;
        this.imageLocation = imageLocation;
    }

    public String getPcid() {
        return this.pcid;
    }

    public void setPcid(String pcid) {
        this.pcid = pcid;
    }

    public String getLbcid() {
        return this.lbcid;
    }

    public void setLbcid(String lbcid) {
        this.lbcid = lbcid;
    }

    public String getBuyingcenter() {
        return this.buyingcenter;
    }

    public void setBuyingcenter(String buyingcenter) {
        this.buyingcenter = buyingcenter;
    }

    public String getNames() {
        return this.names;
    }

    public void setNames(String names) {
        this.names = names;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getTel() {
        return this.tel;
    }

    public void setTel(String tel) {
        this.tel = tel;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public String getImageLocation() {
        return this.imageLocation;
    }

    public void setImageLocation(String imageLocation) {
        this.imageLocation = imageLocation;
    }


}


