package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Supplier generated by hbm2java
 */
public class Supplier implements java.io.Serializable {


    public Integer id;
    public String suppliername;
    public String district;
    public String address;
    public String contactno;
    public String note;
    public String users;
    public Date dates;

    public Supplier() {
    }

    public Supplier(String suppliername, String district, String address, String contactno, String note, String users, Date dates) {
        this.suppliername = suppliername;
        this.district = district;
        this.address = address;
        this.contactno = contactno;
        this.note = note;
        this.users = users;
        this.dates = dates;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getSuppliername() {
        return this.suppliername;
    }

    public void setSuppliername(String suppliername) {
        this.suppliername = suppliername;
    }

    public String getDistrict() {
        return this.district;
    }

    public void setDistrict(String district) {
        this.district = district;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getContactno() {
        return this.contactno;
    }

    public void setContactno(String contactno) {
        this.contactno = contactno;
    }

    public String getNote() {
        return this.note;
    }

    public void setNote(String note) {
        this.note = note;
    }

    public String getUsers() {
        return this.users;
    }

    public void setUsers(String users) {
        this.users = users;
    }

    public Date getDates() {
        return this.dates;
    }

    public void setDates(Date dates) {
        this.dates = dates;
    }


}


