package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord;

/**
 * Farmers generated by hbm2java
 */
public class Templates extends SugarRecord {
    public String template;

    public Templates() {
    }

    public Templates(String template) {
        this.template = template;
    }

    public String getTemplate() {
        return template;
    }

    public void setTemplate(String template) {
        this.template = template;
    }
}


