package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Temptable generated by hbm2java
 */
public class Temptable implements java.io.Serializable {


    public Integer transid;
    public String item;
    public int quantity;
    public BigDecimal unitprice;
    public BigDecimal total;
    public BigDecimal appliedsubsidy;
    public BigDecimal balance;

    public Temptable() {
    }

    public Temptable(String item, int quantity, BigDecimal unitprice, BigDecimal total, BigDecimal appliedsubsidy, BigDecimal balance) {
        this.item = item;
        this.quantity = quantity;
        this.unitprice = unitprice;
        this.total = total;
        this.appliedsubsidy = appliedsubsidy;
        this.balance = balance;
    }

    public Integer getTransid() {
        return this.transid;
    }

    public void setTransid(Integer transid) {
        this.transid = transid;
    }

    public String getItem() {
        return this.item;
    }

    public void setItem(String item) {
        this.item = item;
    }

    public int getQuantity() {
        return this.quantity;
    }

    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }

    public BigDecimal getUnitprice() {
        return this.unitprice;
    }

    public void setUnitprice(BigDecimal unitprice) {
        this.unitprice = unitprice;
    }

    public BigDecimal getTotal() {
        return this.total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public BigDecimal getAppliedsubsidy() {
        return this.appliedsubsidy;
    }

    public void setAppliedsubsidy(BigDecimal appliedsubsidy) {
        this.appliedsubsidy = appliedsubsidy;
    }

    public BigDecimal getBalance() {
        return this.balance;
    }

    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }


}


