package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import com.orm.SugarRecord;

import java.util.Date;

/**
 * Userbiometrics generated by hbm2java
 */
public class Userbiometrics extends SugarRecord {
    public String farmerid;
    public byte[] picture;
    public byte[] signature;
    public String height;
    public String eyecolor;
    public Date createdDate;
    public String placeOfRegistered;
    public Date datecreatedserver;
    public String uniqueuid;
    public String synstatus;
    public Date datecreated;
    public int serverid;
    public String macaddress;
    public String imei;
    public String agentname;
    public String agentid;

    public Userbiometrics(String farmerid, byte[] picture, byte[] signature, String height, String eyecolor, Date createdDate, String placeOfRegistered, Date datecreatedserver, String uniqueuid, String synstatus, Date datecreated, int serverid, String macaddress, String imei, String agentname, String agentid) {
        this.farmerid = farmerid;
        this.picture = picture;
        this.signature = signature;
        this.height = height;
        this.eyecolor = eyecolor;
        this.createdDate = createdDate;
        this.placeOfRegistered = placeOfRegistered;
        this.datecreatedserver = datecreatedserver;
        this.uniqueuid = uniqueuid;
        this.synstatus = synstatus;
        this.datecreated = datecreated;
        this.serverid = serverid;
        this.macaddress = macaddress;
        this.imei = imei;
        this.agentname = agentname;
        this.agentid = agentid;
    }

    public Userbiometrics() {
    }

    public Userbiometrics(String farmerid, byte[] picture, byte[] signature, String height, String eyecolor, Date createdDate, String placeOfRegistered, Date datecreated) {
        this.farmerid = farmerid;
        this.picture = picture;
        this.signature = signature;
        this.height = height;
        this.eyecolor = eyecolor;
        this.createdDate = createdDate;
        this.placeOfRegistered = placeOfRegistered;
        this.datecreatedserver = datecreated;
    }
    public String aggregatorid;

    public String getAggregatorid() {
        return aggregatorid;
    }

    public void setAggregatorid(String aggregatorid) {
        this.aggregatorid = aggregatorid;
    }
    public String getMacaddress() {
        return macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getImei() {
        return imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getAgentname() {
        return agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public String getAgentid() {
        return agentid;
    }

    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    public int getServerid() {
        return serverid;
    }

    public void setServerid(int serverid) {
        this.serverid = serverid;
    }

    public Date getDatecreated() {
        return datecreated;
    }

    public void setDatecreated(Date datecreated) {
        this.datecreated = datecreated;
    }

    public String getSynstatus() {
        return synstatus;
    }

    public void setSynstatus(String synstatus) {
        this.synstatus = synstatus;
    }

    public Date getDatecreatedserver() {
        return datecreatedserver;
    }

    public void setDatecreatedserver(Date datecreatedserver) {
        this.datecreatedserver = datecreatedserver;
    }

    public String getUniqueuid() {
        return uniqueuid;
    }

    public void setUniqueuid(String uniqueuid) {
        this.uniqueuid = uniqueuid;
    }

    public String getFarmerid() {
        return this.farmerid;
    }

    public void setFarmerid(String farmerid) {
        this.farmerid = farmerid;
    }

    public byte[] getPicture() {
        return this.picture;
    }

    public void setPicture(byte[] picture) {
        this.picture = picture;
    }

    public byte[] getSignature() {
        return this.signature;
    }

    public void setSignature(byte[] signature) {
        this.signature = signature;
    }

    public String getHeight() {
        return this.height;
    }

    public void setHeight(String height) {
        this.height = height;
    }

    public String getEyecolor() {
        return this.eyecolor;
    }

    public void setEyecolor(String eyecolor) {
        this.eyecolor = eyecolor;
    }

    public Date getCreatedDate() {
        return this.createdDate;
    }

    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    public String getPlaceOfRegistered() {
        return this.placeOfRegistered;
    }

    public void setPlaceOfRegistered(String placeOfRegistered) {
        this.placeOfRegistered = placeOfRegistered;
    }
}


