package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Waybillreceive generated by hbm2java
 */
public class Waybillreceive implements java.io.Serializable {


    public Integer recid;
    public String waybilltrans;
    public String comments;
    public String receivedby;
    public Date datetime;

    public Waybillreceive() {
    }

    public Waybillreceive(String waybilltrans, String comments, String receivedby, Date datetime) {
        this.waybilltrans = waybilltrans;
        this.comments = comments;
        this.receivedby = receivedby;
        this.datetime = datetime;
    }

    public Integer getRecid() {
        return this.recid;
    }

    public void setRecid(Integer recid) {
        this.recid = recid;
    }

    public String getWaybilltrans() {
        return this.waybilltrans;
    }

    public void setWaybilltrans(String waybilltrans) {
        this.waybilltrans = waybilltrans;
    }

    public String getComments() {
        return this.comments;
    }

    public void setComments(String comments) {
        this.comments = comments;
    }

    public String getReceivedby() {
        return this.receivedby;
    }

    public void setReceivedby(String receivedby) {
        this.receivedby = receivedby;
    }

    public Date getDatetime() {
        return this.datetime;
    }

    public void setDatetime(Date datetime) {
        this.datetime = datetime;
    }


}


