package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Waybill generated by hbm2java
 */
public class Waybill implements java.io.Serializable {


    public Integer id;
    public String waybilltrans;
    public String companyid;
    public String companyname;
    public String distributorid;
    public String distributorname;
    public Date dispdate;
    public Date expectdate;
    public String vehicleno;
    public String vehicletype;
    public String drivername;
    public String issuedby;
    public String checkedby;
    public Date dateissued;
    public String received;
    public String macaddress;
    public String imei;
    public String agentname;
    public String agentid;

    public Waybill() {
    }

    public Waybill(String waybilltrans, String companyid, String companyname, String distributorid, String distributorname, Date dispdate, Date expectdate, String vehicleno, String vehicletype, String drivername, String issuedby, String checkedby, Date dateissued, String received) {
        this.waybilltrans = waybilltrans;
        this.companyid = companyid;
        this.companyname = companyname;
        this.distributorid = distributorid;
        this.distributorname = distributorname;
        this.dispdate = dispdate;
        this.expectdate = expectdate;
        this.vehicleno = vehicleno;
        this.vehicletype = vehicletype;
        this.drivername = drivername;
        this.issuedby = issuedby;
        this.checkedby = checkedby;
        this.dateissued = dateissued;
        this.received = received;
    }

    public String getMacaddress() {
        return macaddress;
    }

    public void setMacaddress(String macaddress) {
        this.macaddress = macaddress;
    }

    public String getImei() {
        return imei;
    }

    public void setImei(String imei) {
        this.imei = imei;
    }

    public String getAgentname() {
        return agentname;
    }

    public void setAgentname(String agentname) {
        this.agentname = agentname;
    }

    public String getAgentid() {
        return agentid;
    }

    public void setAgentid(String agentid) {
        this.agentid = agentid;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getWaybilltrans() {
        return this.waybilltrans;
    }

    public void setWaybilltrans(String waybilltrans) {
        this.waybilltrans = waybilltrans;
    }

    public String getCompanyid() {
        return this.companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }

    public String getCompanyname() {
        return this.companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    public String getDistributorid() {
        return this.distributorid;
    }

    public void setDistributorid(String distributorid) {
        this.distributorid = distributorid;
    }

    public String getDistributorname() {
        return this.distributorname;
    }

    public void setDistributorname(String distributorname) {
        this.distributorname = distributorname;
    }

    public Date getDispdate() {
        return this.dispdate;
    }

    public void setDispdate(Date dispdate) {
        this.dispdate = dispdate;
    }

    public Date getExpectdate() {
        return this.expectdate;
    }

    public void setExpectdate(Date expectdate) {
        this.expectdate = expectdate;
    }

    public String getVehicleno() {
        return this.vehicleno;
    }

    public void setVehicleno(String vehicleno) {
        this.vehicleno = vehicleno;
    }

    public String getVehicletype() {
        return this.vehicletype;
    }

    public void setVehicletype(String vehicletype) {
        this.vehicletype = vehicletype;
    }

    public String getDrivername() {
        return this.drivername;
    }

    public void setDrivername(String drivername) {
        this.drivername = drivername;
    }

    public String getIssuedby() {
        return this.issuedby;
    }

    public void setIssuedby(String issuedby) {
        this.issuedby = issuedby;
    }

    public String getCheckedby() {
        return this.checkedby;
    }

    public void setCheckedby(String checkedby) {
        this.checkedby = checkedby;
    }

    public Date getDateissued() {
        return this.dateissued;
    }

    public void setDateissued(Date dateissued) {
        this.dateissued = dateissued;
    }

    public String getReceived() {
        return this.received;
    }

    public void setReceived(String received) {
        this.received = received;
    }


}


