package com.telpo.usb.finger.entities;
// Generated Dec 14, 2017 8:28:43 PM by Hibernate Tools 4.3.1


/**
 * Wayitem generated by hbm2java
 */
public class Wayitem implements java.io.Serializable {


    public Integer itemid;
    public String companyid;
    public String itemname;
    public String itemdesc;
    public double itemweight;
    public String quantity;
    public String waybilltrans;

    public Wayitem() {
    }

    public Wayitem(String companyid, String itemname, String itemdesc, double itemweight, String quantity, String waybilltrans) {
        this.companyid = companyid;
        this.itemname = itemname;
        this.itemdesc = itemdesc;
        this.itemweight = itemweight;
        this.quantity = quantity;
        this.waybilltrans = waybilltrans;
    }

    public Integer getItemid() {
        return this.itemid;
    }

    public void setItemid(Integer itemid) {
        this.itemid = itemid;
    }

    public String getCompanyid() {
        return this.companyid;
    }

    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }

    public String getItemname() {
        return this.itemname;
    }

    public void setItemname(String itemname) {
        this.itemname = itemname;
    }

    public String getItemdesc() {
        return this.itemdesc;
    }

    public void setItemdesc(String itemdesc) {
        this.itemdesc = itemdesc;
    }

    public double getItemweight() {
        return this.itemweight;
    }

    public void setItemweight(double itemweight) {
        this.itemweight = itemweight;
    }

    public String getQuantity() {
        return this.quantity;
    }

    public void setQuantity(String quantity) {
        this.quantity = quantity;
    }

    public String getWaybilltrans() {
        return this.waybilltrans;
    }

    public void setWaybilltrans(String waybilltrans) {
        this.waybilltrans = waybilltrans;
    }


}


